import type { Metadata } from "next";
import { Alegreya, Alex_Brush, Lato } from 'next/font/google'
import "./globals.css";
import Navbar from '@/components/Navbar/Navbar'

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ['latin'],
  display: 'swap',
  //👇 Add variable to our object
  variable: '--font-lato',
})

const alex_brush = Alex_Brush({
  weight: ["400"],
  subsets: ['latin'],
  display: 'swap',
  //👇 Add variable to our object
  variable: '--font-abrush',
})

const alegreya = Alegreya({
  weight: ["400", "700", "900"],
  subsets: ['latin'],
  display: 'swap',
  //👇 Add variable to our object
  variable: '--font-alegreya',
})

export const metadata: Metadata = {
  title: "Alix Fuerst Art",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
